version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 8
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 120
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 5
  similar-code:
    enabled: false
  identical-code:
    enabled: false
