version: '2'
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 20
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 64
exclude_patterns:
  - '.git/'
  - '.github/'
  - '.idea/'
  - 'coverage/'
  - 'dist/'
  - 'docs/'
  - 'node_modules/'
  - 'src/tests/'
plugins:
  eslint:
    enabled: false
  nodesecurity:
    enabled: false
