name: Label Approved

on:
  pull_request_review: {}
  pull_request:
    types:
      - ready_for_review
      - synchronize
  push:
    branches-ignore:
      - master
      - gh-pages
    tags-ignore:
      - '*'

jobs:
  label_when_approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@1.0.5
        env:
          APPROVALS: 1
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADD_LABEL: '${{ secrets.NEW_PR_AUTOMERGE_LABEL }}'
