name: Label Approved

on:
  pull_request_review: {}
  pull_request:
    types:
      - ready_for_review
      - synchronize
  push:
    branches-ignore:
      - master
      - gh-pages
    tags-ignore:
      - '*'

jobs:
  label_when_approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        uses: TobKed/label-when-approved-action@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
        env:
          APPROVALS: 1
          label: '${{ secrets.NEW_PR_AUTOMERGE_LABEL }}'
          pullRequestNumber: ${{ steps.source-run-info.outputs.pullRequestNumber }}
