name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Lint the codebase
        run: npm run lint:ci
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm run test:ci
      - name: Upload coverage
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test_coverage
          path: coverage
  build_code:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm run build:ci
      - name: Upload dist
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: dist
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: build_code
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run integration tests
        run: npm run test:integration:ci
  build_docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build storybook
        run: npm run docs:ci
      - name: Upload the storybook
        uses: actions/upload-artifact@v2.2.4
        with:
          name: docs
          path: docs
  deploy_docs:
    needs: build_docs
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Download storybook
        uses: actions/download-artifact@v2.0.10
        with:
          name: docs
          path: docs
      - name: Deploy Docs to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: 'gh-pages'
          build_dir: docs
          committer_name: 'GitHub Action'
          committer_email: 'github@devlato.com'
          commit_message: 'Update the Docs on GitHub Pages'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          GITHUB_PAT: '${{ secrets.GH_PAT }}'
  publish:
    needs: [lint, test, build_code, build_docs]
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_AUTH_TOKEN }}'
  update_changelog:
    needs: [publish]
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Generate changelog
        uses: ahmadawais/action-auto-changelog@1.0.0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
